"""Generates the Granumid source files the tests play back."""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
TMP = os.path.join(HERE, '_tmp')


def write(name, notes, length, tempo=120.0, ts=(4, 4), markers=()):
    os.makedirs(TMP, exist_ok=True)
    lines = ['# generated by tests/fixtures.py', '7473', '1', '%.6f' % length,
             str(len(notes)), '%.6f' % tempo, str(ts[0]), str(ts[1]),
             str(len(markers)), '0, 0, 0, 0']
    lines += ['%.6f, %.6f, %d, %d, %d' % n for n in notes]
    lines += ['%.6f' % m for m in markers]
    path = os.path.join(TMP, name)
    open(path, 'w').write('\n'.join(lines) + '\n')
    return path


def arp():
    """8 notes, one every half beat, cycling 60/63/67/70 with falling velocity."""
    notes = [(i * 0.5, 0.45, 60 + [0, 3, 7, 10][i % 4], 100 - (i % 4) * 10, 0) for i in range(8)]
    return write('arp.txt', notes, 4.0, markers=(2.0,))


def flat():
    """8 identical notes - isolates the envelope from source velocity."""
    return write('flat.txt', [(i * 0.5, 0.2, 60, 127, 0) for i in range(8)], 4.0)
