--[[
  granumid_import.lua
  Imports MIDI into Granumid's source format.

  Run it with one or more MIDI items selected to capture them, or with nothing
  selected to pick a Standard MIDI File from disk.  The result is written to

      <REAPER resource path>/Data/granumid/<name>.txt

  which is exactly the folder Granumid's "Source File" selector browses.

  Copyright (C) 2026  Granumid contributors.  GPL v3.
--]]

local MAGIC, VERSION = 7473, 1
local MAX_NOTES = 32768

-- ---------------------------------------------------------------------------
-- helpers
-- ---------------------------------------------------------------------------
local function msg(s) reaper.ShowMessageBox(s, "Granumid Import", 0) end

local function sanitize(name)
  name = name:gsub("[^%w%-%_%. ]", "_"):gsub("^%s+", ""):gsub("%s+$", "")
  if name == "" then name = "phrase" end
  if not name:lower():match("%.txt$") then name = name .. ".txt" end
  return name
end

local function out_dir()
  local dir = reaper.GetResourcePath() .. "/Data/granumid"
  reaper.RecursiveCreateDirectory(dir, 0)
  return dir
end

-- A phrase is { notes = {{start,len,pitch,vel,chan}, ...}, markers = {...},
--               length, tempo, tsnum, tsden, name }
local function new_phrase()
  return { notes = {}, markers = {}, length = 0, tempo = 120, tsnum = 4, tsden = 4, name = "phrase" }
end

local function add_note(ph, st, len, pitch, vel, chan)
  if #ph.notes >= MAX_NOTES then return end
  if len < 0.0005 then len = 0.0005 end
  if st < 0 then len = len + st; st = 0 end
  if len <= 0 then return end
  ph.notes[#ph.notes + 1] = {
    st, len,
    math.max(0, math.min(127, math.floor(pitch))),
    math.max(1, math.min(127, math.floor(vel))),
    math.max(0, math.min(15, math.floor(chan))),
  }
end

local function finish(ph)
  table.sort(ph.notes, function(a, b)
    if a[1] == b[1] then return a[3] < b[3] end
    return a[1] < b[1]
  end)
  local last = 0
  for _, n in ipairs(ph.notes) do last = math.max(last, n[1] + n[2]) end
  if ph.length < last then ph.length = last end
  if ph.length <= 0 then ph.length = math.max(1, math.ceil(last)) end
  table.sort(ph.markers)
  -- drop markers outside the phrase and de-duplicate
  local m, seen = {}, {}
  for _, t in ipairs(ph.markers) do
    local k = string.format("%.4f", t)
    if t > 0.0001 and t < ph.length - 0.0001 and not seen[k] then
      seen[k] = true
      m[#m + 1] = t
    end
  end
  ph.markers = m
end

local function write_phrase(ph, path)
  local f, err = io.open(path, "wb")
  if not f then return false, err end
  local w = {}
  w[#w + 1] = "# Granumid MIDI source"
  w[#w + 1] = "# " .. ph.name
  w[#w + 1] = "# generated by granumid_import.lua"
  w[#w + 1] = "#"
  w[#w + 1] = "# header: magic version lengthBeats noteCount tempo tsNum tsDen markerCount + 4 reserved"
  w[#w + 1] = string.format("%d", MAGIC)
  w[#w + 1] = string.format("%d", VERSION)
  w[#w + 1] = string.format("%.6f", ph.length)
  w[#w + 1] = string.format("%d", #ph.notes)
  w[#w + 1] = string.format("%.6f", ph.tempo)
  w[#w + 1] = string.format("%d", ph.tsnum)
  w[#w + 1] = string.format("%d", ph.tsden)
  w[#w + 1] = string.format("%d", #ph.markers)
  w[#w + 1] = "0, 0, 0, 0"
  w[#w + 1] = "# notes: startBeat, lengthBeats, pitch, velocity, channel"
  for _, n in ipairs(ph.notes) do
    w[#w + 1] = string.format("%.6f, %.6f, %d, %d, %d", n[1], n[2], n[3], n[4], n[5])
  end
  if #ph.markers > 0 then
    w[#w + 1] = "# slice markers (beats)"
    for _, t in ipairs(ph.markers) do w[#w + 1] = string.format("%.6f", t) end
  end
  f:write(table.concat(w, "\n"), "\n")
  f:close()
  return true
end

-- ---------------------------------------------------------------------------
-- capture from selected media items
-- ---------------------------------------------------------------------------
local function collect_items()
  local items = {}
  for i = 0, reaper.CountSelectedMediaItems(0) - 1 do
    local it = reaper.GetSelectedMediaItem(0, i)
    local take = reaper.GetActiveTake(it)
    if take and reaper.TakeIsMIDI(take) then items[#items + 1] = { it, take } end
  end
  return items
end

local function phrase_from_items(items)
  local ph = new_phrase()

  local first, last = math.huge, -math.huge
  for _, e in ipairs(items) do
    local pos = reaper.GetMediaItemInfo_Value(e[1], "D_POSITION")
    local len = reaper.GetMediaItemInfo_Value(e[1], "D_LENGTH")
    first = math.min(first, pos)
    last  = math.max(last, pos + len)
  end

  local baseQN = reaper.TimeMap2_timeToQN(0, first)
  ph.length = reaper.TimeMap2_timeToQN(0, last) - baseQN

  local tsnum, tsden, bpm = reaper.TimeMap_GetTimeSigAtTime(0, first)
  ph.tsnum = math.floor(tsnum or 4)
  ph.tsden = math.floor(tsden or 4)
  ph.tempo = bpm or reaper.Master_GetTempo()

  local _, itemName = reaper.GetSetMediaItemTakeInfo_String(items[1][2], "P_NAME", "", false)
  ph.name = (itemName ~= "" and itemName) or "phrase"

  for _, e in ipairs(items) do
    local item, take = e[1], e[2]
    local _, noteCount = reaper.MIDI_CountEvts(take)
    for n = 0, noteCount - 1 do
      local ok, _, muted, sppq, eppq, chan, pitch, vel = reaper.MIDI_GetNote(take, n)
      if ok and not muted then
        local s = reaper.MIDI_GetProjQNFromPPQPos(take, sppq) - baseQN
        local e2 = reaper.MIDI_GetProjQNFromPPQPos(take, eppq) - baseQN
        add_note(ph, s, e2 - s, pitch, vel, chan)
      end
    end

    -- take markers (positions are in source time, scaled by the take playrate)
    local rate = reaper.GetMediaItemTakeInfo_Value(take, "D_PLAYRATE")
    if rate == 0 then rate = 1 end
    local offs = reaper.GetMediaItemTakeInfo_Value(take, "D_STARTOFFS")
    local ipos = reaper.GetMediaItemInfo_Value(item, "D_POSITION")
    local nmk = reaper.GetNumTakeMarkers and reaper.GetNumTakeMarkers(take) or 0
    for k = 0, nmk - 1 do
      local src = reaper.GetTakeMarker(take, k)
      if src and src >= 0 then
        local t = ipos + (src - offs) / rate
        ph.markers[#ph.markers + 1] = reaper.TimeMap2_timeToQN(0, t) - baseQN
      end
    end
  end

  -- project markers that fall inside the captured span
  local total = reaper.CountProjectMarkers(0)
  for i = 0, total - 1 do
    local ok, isrgn, pos = reaper.EnumProjectMarkers(i)
    if ok ~= 0 and not isrgn and pos > first and pos < last then
      ph.markers[#ph.markers + 1] = reaper.TimeMap2_timeToQN(0, pos) - baseQN
    end
  end

  finish(ph)
  return ph
end

-- ---------------------------------------------------------------------------
-- Standard MIDI File reader
-- ---------------------------------------------------------------------------
local SMF = {}
SMF.__index = SMF

local function reader(data)
  return setmetatable({ d = data, p = 1 }, SMF)
end

function SMF:u8()
  local b = self.d:byte(self.p)
  self.p = self.p + 1
  return b or 0
end

function SMF:u16() return self:u8() * 256 + self:u8() end

function SMF:u32()
  local v = 0
  for _ = 1, 4 do v = v * 256 + self:u8() end
  return v
end

function SMF:str(n)
  local s = self.d:sub(self.p, self.p + n - 1)
  self.p = self.p + n
  return s
end

function SMF:varlen()
  local v, b = 0, 0
  repeat
    b = self:u8()
    v = v * 128 + (b % 128)
  until b < 128
  return v
end

local function parse_smf(data)
  local r = reader(data)
  if r:str(4) ~= "MThd" then return nil, "not a Standard MIDI File (no MThd chunk)" end
  local hlen   = r:u32()
  local _      = r:u16()          -- format
  local ntrks  = r:u16()
  local div    = r:u16()
  r.p = r.p + (hlen - 6)

  local ticksPerQN
  if div >= 0x8000 then
    -- SMPTE division: ticks are absolute time, convert via the first tempo later
    local fps = 256 - math.floor(div / 256)
    local tpf = div % 256
    ticksPerQN = nil
    r.smpte = fps * tpf                       -- ticks per second
  else
    ticksPerQN = div
  end
  if ticksPerQN == 0 then ticksPerQN = 96 end

  local ph = new_phrase()
  local firstTempo, endTick = nil, 0

  for _ = 1, ntrks do
    if r.p > #data then break end
    local id = r:str(4)
    local tlen = r:u32()
    local tend = r.p + tlen
    if id ~= "MTrk" then
      r.p = tend
    else
      local tick, running = 0, 0
      local open = {}                          -- open[chan*128+pitch] = {tick, vel}
      while r.p < tend do
        tick = tick + r:varlen()
        local b = r:u8()
        local status, d1
        if b < 0x80 then
          status = running
          d1 = b
        else
          status = b
          running = (b < 0xF0) and b or running
          d1 = nil
        end

        local hi = status - (status % 16)
        if status == 0xFF then
          local mt = r:u8()
          local ln = r:varlen()
          if mt == 0x51 and ln == 3 then
            local t = r:u8() * 65536 + r:u8() * 256 + r:u8()
            if not firstTempo and t > 0 then firstTempo = 60000000 / t end
          elseif mt == 0x58 and ln >= 2 then
            local num = r:u8()
            local den = math.floor(2 ^ r:u8())
            r.p = r.p + (ln - 2)
            if ph.tsnum == 4 and ph.tsden == 4 then ph.tsnum, ph.tsden = num, den end
          elseif mt == 0x06 or mt == 0x01 then
            -- marker / text: only markers become slice points
            local txt = r:str(ln)
            if mt == 0x06 then ph.markers[#ph.markers + 1] = tick end
            local _ = txt
          else
            r.p = r.p + ln
          end
        elseif status == 0xF0 or status == 0xF7 then
          r.p = r.p + r:varlen()
        elseif hi == 0x80 or hi == 0x90 or hi == 0xA0 or hi == 0xB0 or hi == 0xE0 then
          local a = d1 or r:u8()
          local bb = r:u8()
          local chan = status % 16
          if hi == 0x90 and bb > 0 then
            open[chan * 128 + a] = { tick, bb }
          elseif hi == 0x80 or (hi == 0x90 and bb == 0) then
            local o = open[chan * 128 + a]
            if o then
              ph.notes[#ph.notes + 1] = { o[1], tick - o[1], a, o[2], chan }   -- ticks for now
              open[chan * 128 + a] = nil
            end
          end
        elseif hi == 0xC0 or hi == 0xD0 then
          local _ = d1 or r:u8()
        else
          -- unknown status: bail out of this track rather than desync
          r.p = tend
        end
        endTick = math.max(endTick, tick)
      end
      r.p = tend
    end
  end

  ph.tempo = firstTempo or 120

  -- convert ticks -> beats
  local scale
  if ticksPerQN then
    scale = 1 / ticksPerQN
  else
    scale = ph.tempo / 60 / r.smpte            -- ticks/sec -> beats
  end

  local converted = {}
  for _, n in ipairs(ph.notes) do
    local st = n[1] * scale
    local ln = math.max(n[2] * scale, 0.0005)
    converted[#converted + 1] = {
      st, ln,
      math.max(0, math.min(127, n[3])),
      math.max(1, math.min(127, n[4])),
      math.max(0, math.min(15, n[5])),
    }
  end
  ph.notes = converted
  for i, t in ipairs(ph.markers) do ph.markers[i] = t * scale end
  ph.length = endTick * scale
  if ph.length <= 0 then ph.length = 4 end

  -- round the phrase out to a whole bar so loops line up musically
  local bar = ph.tsnum * 4 / ph.tsden
  if bar > 0 then ph.length = math.ceil(ph.length / bar - 0.0001) * bar end

  finish(ph)
  return ph
end

-- ---------------------------------------------------------------------------
-- main
-- ---------------------------------------------------------------------------
local function main()
  local items = collect_items()
  local ph

  if #items > 0 then
    ph = phrase_from_items(items)
  else
    local ok, path = reaper.GetUserFileNameForRead("", "Granumid: choose a MIDI file", ".mid")
    if not ok then return end
    local f = io.open(path, "rb")
    if not f then msg("Could not open:\n" .. path) return end
    local data = f:read("*a")
    f:close()
    local err
    ph, err = parse_smf(data)
    if not ph then msg("Could not read that file:\n" .. tostring(err)) return end
    ph.name = path:match("([^/\\]+)%.[Mm][Ii][Dd][Ii]?$") or path:match("([^/\\]+)$") or "phrase"
  end

  if #ph.notes == 0 then msg("No notes were found - nothing to import.") return end

  local ok, name = reaper.GetUserInputs("Granumid Import", 1, "Save as (in Data/granumid),extrawidth=140", ph.name)
  if not ok then return end

  local file = sanitize(name)
  local path = out_dir() .. "/" .. file
  local wrote, werr = write_phrase(ph, path)
  if not wrote then msg("Could not write:\n" .. path .. "\n\n" .. tostring(werr)) return end

  msg(string.format(
    "Imported %d notes (%.2f beats, %d markers) at %.1f BPM %d/%d.\n\n%s\n\n" ..
    "Pick it from Granumid's Source File selector.",
    #ph.notes, ph.length, #ph.markers, ph.tempo, ph.tsnum, ph.tsden, path))
end

reaper.Undo_BeginBlock()
main()
reaper.Undo_EndBlock("Granumid: import MIDI source", -1)
